
(defun latex-symbols-prettify ()
  "A long list of symbols to display nicely in latex-mode"
  (mapc (lambda (pair) (add-to-list 'prettify-symbols-alist pair))
        ;; ARROWS
        '(("\\to"                  32 (Br . Bl) 32 (Br . Br) 57620)
          ("\\rightarrow"          32 (Br . Bl) 32 (Br . Br) 57620)
          ("\\mapsto"              8870 (cr  cl 16 0) 57620)
          ("\\longmapsto"          32 (Br . Bl)  8866 (cr . cl) 32 (Br . Bl)  32 (Br . Br)  57619)
          ("\\inj"                 5308 (tl  tl 20 0) 32 (tr  tl 0 -5) 57620)
          ("\\emb"                 5308 (tl  tl 20 0) 32 (tr  tl 0 5) 57620)
          ("\\hookrightarrow"      5354 (tl . tl) 32 (tr . tl) 57620)
          ("\\surj"                32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57621)
          ("\\proj"                32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57621)
          ("\\twoheadrightarrow"   32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57621)
          ("\\twoheadleftarrow"    32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57693)
          ("\\longrightarrow"      32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57619)
          ("\\rightsquigarrow"     32 (Br . Bl) 32 (Br . Br) 57703)
          ("\\leftarrow"           32 (Br . Bl) 32 (Br . Br) 57682)
          ("\\longleftarrow"       32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57683)
          ("\\leftrightarrow"      32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57684)
          ("\\leftsquigarrow"      32 (Br . Bl) 32 (Br . Br) 57696)
          ("\\Rightarrow"          32 (Br . Bl) 32 (Br . Br) 57663)
          ("\\Longrightarrow"      32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57662)
          ("\\implies"             32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57662)
          ("\\Leftarrow"           32 (Br . Bl) 32 (Br . Br) 57688)
          ("\\Longleftarrow"       32 (Br . Bl) 32 (Br . Br) 57688)
          ("\\impliedby"           32 (Br . Bl) 32 (Br . Br) 57688)
          ("\\Leftrightarrow"      32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57689)
          ("\\upharpoonleft"       ?↿)
          ("\\upharpoonright"      ?↾)
          ("\\downharpoonleft"     ?⇃)
          ("\\downharpoonright"    ?⇂)
          ("\\hookleftarrow"       ?↩)
          ("\\looparrowleft"       ?↫)
          ("\\looparrowright"      ?↬)
          ("\\leftrightsquigarrow" ?↭)
          ("\\leftleftarrows"      ?⇇)
          ("\\rightrightarrows"    ?⇉)
          ("\\leftrightarrows"     ?⇆)
          ("\\rightleftarrows"     ?⇄)
          ("\\Lleftarrow"         ?⇚)
          ("\\Rrightarrow"        ?⇛)
          ;; ENVIRONMENTS
          ("\\part"                ?#)
          ("\\section"             32 (Br . Bl) 32 (Br . Br) 57627)
          ("\\subsection"          32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57628)
          ("\\subsubsection"       32 (Br . Bl) 32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57629)
          ("\\begin"               32 (Br . Bl) 32 (Br . Br) 57653)
          ("\\end"                 32 (Br . Bl) 32 (Br . Br) 57677)
          ("\\item"                32 (Br . Bl) 32 (Br . Bl) 32 (Br . Br) 57686)
          ;; SPACING
          ("\\,"                  8194 (Bc . Bc) 8231)
          ("\\:"                  8194 (Bc . Bc) 8231)
          ("\\;"                  8194 (Bc . Bc) 8231)
          ("\\enspace"            8194 (Bc . Bc) 8231)
          ("\\emspace"            8195 (Bc . Bc) 8231)
          ("\\quad"               8231 (Bc . Bc) 8195 (Br . Bl) 8231 (Bc . Bc) 8195)
          ("\\qquad"              8231 (Bc . Bc) 8195 (Br . Bl) 8231 (Bc . Bc) 8195 (Br . Bl) 8231 (Bc . Bc) 8195 (Br . Bl) 8231 (Bc . Bc) 8195)
          ;; SETS
          ("\\mathbb{N}"           ?\u2115)
          ("\\mathbb{R}"           ?\u211D)
          ("\\mathbb{C}"           8450)
          ("\\mathbb{P}"           8473)
          ("\\mathcal{C}"          120018)
          ("\\cat{C}"              120018)
          ("\\mathcal{D}"          120019)
          ("\\cat{D}"              120019)
          ("\\cat{E}"              120020)
          ("\\cat{M}"              120028)
          ("\\cat{N}"              120029)
          ("\\mathfrak{C}"         120174)
          ("\\mathfrak{D}"         120175)
          ("\\ZCat"                120041)
          ;; OPERATORS
          ("\\defeq"               32 (Br . Bl) 32 (Br . Br) 57612)
          ("\\eq"                  ?=)
          ("\\neq"                 32 (Br . Bl) 32 (Br . Br) 57614)
          ("\\blank"               8212)
          ("\\from"                32 (Br . Br) 57708)
          ("\\colon"               32 (Br . Br) 57708)
          ("\\lact"                9655)
          ("\\blact"               9654)
          ("\\ract"                9665)
          ("\\bract"               9664)
          ("\\unlhd"               ?⊴)
          ("\\unrhd"               ?⊵)
          ("\\cdot "               8226)
          (" \\cdot "              8226)
          ("\\times "              215)
          (" \\times "             215)
          ("\\parallel"            ?∥)
          ("\\notni"               8260 (cc . cc) ?∋)
          ("\\sqcup"               ?⊔)
          ("\\bigsqcup"            ?⊔)
          ("\\sqcap"               ?⊓)
          ("\\bigsqcap"            ?⊓)
          ("\\biguplus"            ?⨄)
          ("\\land"                ?∧)
          ("\\lor"                 ?∨)
          ("\\odot"                ?⊙)
          ("\\bigodot"             ?⊙)
          ("\\otimes"              ?⊗)
          ("\\bigotimes"           ?⊗)
          ("\\oplus"               ?⊕)
          ("\\bigoplus"            ?⊕)
          ("\\sqrt"                ?√)
          ("\\iint"                ?∬)
          ("\\iiint"               ?∭)
          ("\\iiiint"              ?⨌)
          ("\\oiint"               ?∯)
          ("\\oiiint"              ?∰)
          ("\\ointclockwise"       ?∲)
          ("\\ointctrclockwise"    ?∳)
          ;; BETTER SUB AND SUPERSCRIPTS
          ("^0"                    8304)
          ("^1"                    185)
          ("^2"                    178)
          ("^3"                    179)
          ("^4"                    8308)
          ("^5"                    8309)
          ("^6"                    8310)
          ("^7"                    8311)
          ("^8"                    8312)
          ("^9"                    8313)
          ("^l"                    ?\u02E1)
          ("^r"                    ?\u02B3)
          ("^T"                    ?\u1d40)
          ("_0"                    8320)
          ("_1"                    8321)
          ("_2"                    8322)
          ("_3"                    8323)
          ("_4"                    8324)
          ("_5"                    8325)
          ("_6"                    8326)
          ("_7"                    8327)
          ("_8"                    8328)
          ("_9"                    8329)
          ;; GREEK UPPER CASES
          ("\\Alpha"               ?Α)
          ("\\Beta"                ?Β)
          ("\\Gamma"               ?Γ)
          ("\\Delta"               ?Δ)
          ("\\Epsilon"             ?Ε)
          ("\\Zeta"                ?Ζ)
          ("\\Eta"                 ?Η)
          ("\\Theta"               ?Θ)
          ("\\Iota"                ?Ι)
          ("\\Kappa"               ?Κ)
          ("\\Lambda"              ?Λ)
          ("\\Mu"                  ?Μ)
          ("\\Nu"                  ?Ν)
          ("\\Xi"                  ?Ξ)
          ("\\Omicron"             ?Ο)
          ("\\Pi"                  ?Π)
          ("\\Rho"                 ?Ρ)
          ("\\Sigma"               ?Σ)
          ("\\Tau"                 ?Τ)
          ("\\Upsilon"             ?Υ)
          ("\\Phi"                 ?Φ)
          ("\\Chi"                 ?Χ)
          ("\\Psi"                 ?Ψ)
          ("\\Omega"               ?Ω)
          ;; SPECIAL SYMBOLS
          ("\\ss"                  ?ß)
          ("\\aa"                  ?å)
          ("\\AA"                  ?Å)
          ("\\ae"                  ?æ)
          ("\\oe"                  ?œ)
          ("\\AE"                  ?Æ)
          ("\\OE"                  ?Œ)
          ("\\o"                   ?ø)
          ("\\O"                   ?Ø)
          ("\\l"                   ?ł)
          ("\\L"                   ?Ł)
          ("\\S"                   ?§)
          ;; ESCAPED SYMBOLS
          ("\\$"                   ?＄)
          ("\\%"                   ?％)
          ("\\#"                   ?＃)
          ("\\_"                   ?＿)
          ("\\&"                   ?& (Bc . Bc) ?|)
          ;;REFERECING
          ("\\ref"                 ?☞)
          ("\\cite"                ?†)
          ("\\footnote"            ?‡)
          ("\\label"               43 (cc . cc) ?‡)
          ("\\TeX"                 ?T (cr cl -20 -45) ?E (cr cl -20 24) ?X)
          ("\\LaTeX"               ?L (cr cl -60 35) ?A (cr cl -18 -20) ?T (cr cl -18 -60) ?E (cr cl -20 5) ?X)
          ;; PARENTHESES
          ("{"                     ?⎨)
          ("}"                     ?⎬)
          ("\\{"                   ?{)
          ("\\}"                   ?})
          ("\\lbrace"              ?{)
          ("\\rbrace"              ?})
          ("\\{"                   ?{)
          ("\\}"                   ?})
          ("\\|"                   ?║)
          ;; Misc
          ("\\dots"                ?…)
          ("\\textbackslash"       ?＼)
          ("\\backslash"           ?＼)
          ("\\qed"                 ?□)
          ("\\lightning"           ?Ϟ)
          ("\\copyright"           ?©)
          ("\\texistregistered"    ?®)
          ("\\texttrademark"       ?™)
          ("\\euro"                8364)
          ("\\pounds"              ?£)
          ("\\lvert"               ?|)
          ("\\rvert"               ?|)
          ("\\lVert"               ?ǁ)
          ("\\rVert"               ?ǁ)
          )))

(provide 'latex-symbols-prettify)
